//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 06:45:25 PM IST 
//


package isu.issuer_ias.xsd.ias_auth;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="strCommand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strXML" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strSignature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "strCommand",
    "strXML",
    "strSignature"
})
@XmlRootElement(name = "CallPaySecure")
public class CallPaySecure {

    @XmlElement(required = true)
    protected String strCommand;
    @XmlElement(required = true)
    protected String strXML;
    @XmlElement(required = true)
    protected String strSignature;

    /**
     * Gets the value of the strCommand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrCommand() {
        return strCommand;
    }

    /**
     * Sets the value of the strCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrCommand(String value) {
        this.strCommand = value;
    }

    /**
     * Gets the value of the strXML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrXML() {
        return strXML;
    }

    /**
     * Sets the value of the strXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrXML(String value) {
        this.strXML = value;
    }

    /**
     * Gets the value of the strSignature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrSignature() {
        return strSignature;
    }

    /**
     * Sets the value of the strSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrSignature(String value) {
        this.strSignature = value;
    }

}
